// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VTInformatica.Data;

#nullable disable

namespace VTInformatica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250410143916_modifiedOrders2")]
    partial class modifiedOrders2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("VTInformatica.Models.Auth.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ffb80785-c550-4f27-9a80-d7b625731f41",
                            ConcurrencyStamp = "ffb80785-c550-4f27-9a80-d7b625731f41",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "cc0babd8-79e4-43a0-9338-4e2ecfc1654f",
                            ConcurrencyStamp = "cc0babd8-79e4-43a0-9338-4e2ecfc1654f",
                            Name = "Seller",
                            NormalizedName = "SELLER"
                        },
                        new
                        {
                            Id = "bf090f13-1b4e-4fa2-8d04-9671fa60dccc",
                            ConcurrencyStamp = "bf090f13-1b4e-4fa2-8d04-9671fa60dccc",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("VTInformatica.Models.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VTInformatica.Models.Auth.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("VTInformatica.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("VTInformatica.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("VTInformatica.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Componenti PC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Periferiche"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accessori e Cavi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 6,
                            Name = "PC Assemblati"
                        });
                });

            modelBuilder.Entity("VTInformatica.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("ManufacturerLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/intel.svg",
                            ManufacturerName = "Intel"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/amd-logo-1.svg",
                            ManufacturerName = "AMD"
                        },
                        new
                        {
                            ManufacturerId = 3,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/nvidia.svg",
                            ManufacturerName = "NVIDIA"
                        },
                        new
                        {
                            ManufacturerId = 4,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/asus-logo.svg",
                            ManufacturerName = "ASUS"
                        },
                        new
                        {
                            ManufacturerId = 5,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/corsair-2.svg",
                            ManufacturerName = "Corsair"
                        },
                        new
                        {
                            ManufacturerId = 6,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/micro-star-international-logo.svg",
                            ManufacturerName = "MSI"
                        },
                        new
                        {
                            ManufacturerId = 7,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/gigabyte-technology-logo-2008.svg",
                            ManufacturerName = "Gigabyte"
                        },
                        new
                        {
                            ManufacturerId = 8,
                            ManufacturerLogo = "https://upload.wikimedia.org/wikipedia/commons/3/34/Thermalright_Logo.svg",
                            ManufacturerName = "ThermalRight"
                        },
                        new
                        {
                            ManufacturerId = 9,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/be-quiet-logo.svg",
                            ManufacturerName = "Be quiet!"
                        },
                        new
                        {
                            ManufacturerId = 10,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/lg-electronics.svg",
                            ManufacturerName = "LG"
                        },
                        new
                        {
                            ManufacturerId = 11,
                            ManufacturerLogo = "https://noctua.at/pub/static/version1743603791/frontend/SIT/noctua/en_US/images/logo.svg",
                            ManufacturerName = "Noctua"
                        },
                        new
                        {
                            ManufacturerId = 12,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/samsung-8.svg",
                            ManufacturerName = "Samsung"
                        },
                        new
                        {
                            ManufacturerId = 13,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/seagate-logo-1.svg",
                            ManufacturerName = "Seagate"
                        },
                        new
                        {
                            ManufacturerId = 14,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/western-digital-2.svg",
                            ManufacturerName = "Western Digital"
                        },
                        new
                        {
                            ManufacturerId = 15,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/kingston-1.svg",
                            ManufacturerName = "Kingston"
                        },
                        new
                        {
                            ManufacturerId = 16,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/crucial.svg",
                            ManufacturerName = "Crucial"
                        },
                        new
                        {
                            ManufacturerId = 17,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/evga.svg",
                            ManufacturerName = "EVGA"
                        },
                        new
                        {
                            ManufacturerId = 18,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/cooler-master-black-logo.svg",
                            ManufacturerName = "Cooler Master"
                        },
                        new
                        {
                            ManufacturerId = 19,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/thermaltake.svg",
                            ManufacturerName = "Thermaltake"
                        },
                        new
                        {
                            ManufacturerId = 20,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/razer-1.svg",
                            ManufacturerName = "Razer"
                        },
                        new
                        {
                            ManufacturerId = 21,
                            ManufacturerLogo = "https://cdn.worldvectorlogo.com/logos/nzxt-1.svg",
                            ManufacturerName = "NZXT"
                        });
                });

            modelBuilder.Entity("VTInformatica.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VTInformatica.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("VTInformatica.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("VTInformatica.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewRating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VTInformatica.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Schede madri"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Schede video"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "SSD / Hard Disk"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Alimentatori"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Case"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Dissipatori"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Tastiere"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Cuffie"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Microfoni"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Webcam"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Controller"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Name = "Volanti"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Name = "Sedie da gaming"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Name = "Accessori RGB"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "Cavi di alimentazione"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Adattatori e hub"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Name = "Ventole"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Name = "Paste termiche"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Name = "Router"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Name = "Schede di rete"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Name = "Range extender"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Name = "Gaming entry-level"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Name = "Gaming mid-range"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Name = "Gaming high-end"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            Name = "Workstation"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Name = "Mini PC"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("VTInformatica.Models.Auth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VTInformatica.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VTInformatica.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VTInformatica.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductImage", b =>
                {
                    b.HasOne("VTInformatica.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VTInformatica.Models.Auth.ApplicationUserRole", b =>
                {
                    b.HasOne("VTInformatica.Models.Auth.ApplicationRole", "Role")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VTInformatica.Models.Auth.ApplicationUser", "User")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTInformatica.Models.Cart", b =>
                {
                    b.HasOne("VTInformatica.Models.Auth.ApplicationUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("VTInformatica.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTInformatica.Models.CartItem", b =>
                {
                    b.HasOne("VTInformatica.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VTInformatica.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VTInformatica.Models.Order", b =>
                {
                    b.HasOne("VTInformatica.Models.Auth.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VTInformatica.Models.OrderItem", b =>
                {
                    b.HasOne("VTInformatica.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VTInformatica.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VTInformatica.Models.Product", b =>
                {
                    b.HasOne("VTInformatica.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VTInformatica.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VTInformatica.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("VTInformatica.Models.Review", b =>
                {
                    b.HasOne("VTInformatica.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VTInformatica.Models.Auth.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTInformatica.Models.SubCategory", b =>
                {
                    b.HasOne("VTInformatica.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VTInformatica.Models.Auth.ApplicationRole", b =>
                {
                    b.Navigation("ApplicationUserRoles");
                });

            modelBuilder.Entity("VTInformatica.Models.Auth.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserRoles");

                    b.Navigation("Cart");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VTInformatica.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VTInformatica.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("VTInformatica.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VTInformatica.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("VTInformatica.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VTInformatica.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
